version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/express-app
file_exists_behavior: OVERWRITE

hooks:

  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ubuntu

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 1000
      runas: ubuntu

  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 600
      runas: ubuntu